-module(configuration).
-export([id_to_name/2, name_to_id/2]).

id_to_name(clientbound, 0) -> 'minecraft:cookie_request';
id_to_name(clientbound, 1) -> 'minecraft:custom_payload';
id_to_name(clientbound, 2) -> 'minecraft:disconnect';
id_to_name(clientbound, 3) -> 'minecraft:finish_configuration';
id_to_name(clientbound, 4) -> 'minecraft:keep_alive';
id_to_name(clientbound, 5) -> 'minecraft:ping';
id_to_name(clientbound, 6) -> 'minecraft:reset_chat';
id_to_name(clientbound, 7) -> 'minecraft:registry_data';
id_to_name(clientbound, 8) -> 'minecraft:resource_pack_pop';
id_to_name(clientbound, 9) -> 'minecraft:resource_pack_push';
id_to_name(clientbound, 10) -> 'minecraft:store_cookie';
id_to_name(clientbound, 11) -> 'minecraft:transfer';
id_to_name(clientbound, 12) -> 'minecraft:update_enabled_features';
id_to_name(clientbound, 13) -> 'minecraft:update_tags';
id_to_name(clientbound, 14) -> 'minecraft:select_known_packs';
id_to_name(clientbound, 15) -> 'minecraft:custom_report_details';
id_to_name(clientbound, 16) -> 'minecraft:server_links';
id_to_name(clientbound, 17) -> 'minecraft:clear_dialog';
id_to_name(clientbound, 18) -> 'minecraft:show_dialog';
id_to_name(clientbound, 19) -> 'minecraft:code_of_conduct';
id_to_name(serverbound, 0) -> 'minecraft:client_information';
id_to_name(serverbound, 1) -> 'minecraft:cookie_response';
id_to_name(serverbound, 2) -> 'minecraft:custom_payload';
id_to_name(serverbound, 3) -> 'minecraft:finish_configuration';
id_to_name(serverbound, 4) -> 'minecraft:keep_alive';
id_to_name(serverbound, 5) -> 'minecraft:pong';
id_to_name(serverbound, 6) -> 'minecraft:resource_pack';
id_to_name(serverbound, 7) -> 'minecraft:select_known_packs';
id_to_name(serverbound, 8) -> 'minecraft:custom_click_action';
id_to_name(serverbound, 9) -> 'minecraft:accept_code_of_conduct';
id_to_name(_, _) -> error(unknown_id).

name_to_id(clientbound, 'minecraft:cookie_request') -> 0;
name_to_id(clientbound, 'minecraft:custom_payload') -> 1;
name_to_id(clientbound, 'minecraft:disconnect') -> 2;
name_to_id(clientbound, 'minecraft:finish_configuration') -> 3;
name_to_id(clientbound, 'minecraft:keep_alive') -> 4;
name_to_id(clientbound, 'minecraft:ping') -> 5;
name_to_id(clientbound, 'minecraft:reset_chat') -> 6;
name_to_id(clientbound, 'minecraft:registry_data') -> 7;
name_to_id(clientbound, 'minecraft:resource_pack_pop') -> 8;
name_to_id(clientbound, 'minecraft:resource_pack_push') -> 9;
name_to_id(clientbound, 'minecraft:store_cookie') -> 10;
name_to_id(clientbound, 'minecraft:transfer') -> 11;
name_to_id(clientbound, 'minecraft:update_enabled_features') -> 12;
name_to_id(clientbound, 'minecraft:update_tags') -> 13;
name_to_id(clientbound, 'minecraft:select_known_packs') -> 14;
name_to_id(clientbound, 'minecraft:custom_report_details') -> 15;
name_to_id(clientbound, 'minecraft:server_links') -> 16;
name_to_id(clientbound, 'minecraft:clear_dialog') -> 17;
name_to_id(clientbound, 'minecraft:show_dialog') -> 18;
name_to_id(clientbound, 'minecraft:code_of_conduct') -> 19;
name_to_id(serverbound, 'minecraft:client_information') -> 0;
name_to_id(serverbound, 'minecraft:cookie_response') -> 1;
name_to_id(serverbound, 'minecraft:custom_payload') -> 2;
name_to_id(serverbound, 'minecraft:finish_configuration') -> 3;
name_to_id(serverbound, 'minecraft:keep_alive') -> 4;
name_to_id(serverbound, 'minecraft:pong') -> 5;
name_to_id(serverbound, 'minecraft:resource_pack') -> 6;
name_to_id(serverbound, 'minecraft:select_known_packs') -> 7;
name_to_id(serverbound, 'minecraft:custom_click_action') -> 8;
name_to_id(serverbound, 'minecraft:accept_code_of_conduct') -> 9;
name_to_id(_, _) -> error(unknown_name).
